### ISSUE TITLE
Duplicate accounts when synchronizing

### ISSUE THREAD

**Issue by nitnelave** [konnectors/boursorama#165]
Every time I synchronize, I get a bunch of errors in the logs, and I end up with an extra copy of my accounts (adding to more and more money, which I wish was real but isn't :( ).

The error logs (edited to remove identifying details):
```
W: Could not parse for
W: Cannot read property '3' of null
W: Failed to create global model:
W: {"errors":[{"status":"404","title":"Not Found","detail":"wanted remote asset is not part of our asset list","source":{}}]}
W: Failed to create local model:
W: Impossible to instanciate a classifier since there is no manually categorized transactions to learn from
E: Stderr: FetchError: {"error":"conflict","ok":false,"reason":"Document update conflict.","status":"409"}
    at CozyStackClient.<anonymous> (/tmp/service-banks692701657/index.js:22:349701)
    at tryCatch (/tmp/service-banks692701657/index.js:22:329033)
    at Generator._invoke (/tmp/service-banks692701657/index.js:22:328807)
    at Generator.e.<computed> [as next] (/tmp/service-banks692701657/index.js:22:329565)
    at asyncGeneratorStep (/tmp/service-banks692701657/index.js:38:33795)
    at _next (/tmp/service-banks692701657/index.js:38:34009)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  response: k [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://mydomain/data/io.cozy.bank.groups/dbc65af4f2723e9791fc66a9b907baac',
      status: 409,
      statusText: 'Conflict',
      headers: [b [Headers]],
      counter: 0
    }
  },
  url: 'https://mydomain/data/io.cozy.bank.groups/dbc65af4f2723e9791fc66a9b907baac',
  status: 409,
  reason: {
    error: 'conflict',
    ok: false,
    reason: 'Document update conflict.',
    status: '409'
  }
}

W: Error while performing job: exit status 1 (retry in 58.474649ms)
E: Stderr: FetchError: {"error":"conflict","ok":false,"reason":"Document update conflict.","status":"409"}
    at CozyStackClient.<anonymous> (/tmp/service-banks909172580/index.js:22:347902)
    at tryCatch (/tmp/service-banks909172580/index.js:22:327234)
    at Generator._invoke (/tmp/service-banks909172580/index.js:22:327008)
    at Generator.e.<computed> [as next] (/tmp/service-banks909172580/index.js:22:327766)
    at asyncGeneratorStep (/tmp/service-banks909172580/index.js:38:33795)
    at _next (/tmp/service-banks909172580/index.js:38:34009)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  response: k [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://mydomain/data/io.cozy.bank.accounts/dbc65af4f2723e9791fc66a9b969e2fd',
      status: 409,
      statusText: 'Conflict',
      headers: [b [Headers]],
      counter: 0
    }
  },
  url: 'https://mydomain/data/io.cozy.bank.accounts/dbc65af4f2723e9791fc66a9b969e2fd',
  status: 409,
  reason: {
    error: 'conflict',
    ok: false,
    reason: 'Document update conflict.',
    status: '409'
  }
}
```

I somehow have 2 versions of boursorama installed on this cozy (1.8.1-56a12982ace7ab6d59dbc79ae04006ff884e0417 and 1.8.1-99f2981f883ace5a1eaece3c421bcb5e129a447d34286459288153292da8ab4f) so I'm not sure which one is running, but I:
 - installed it directly from GH,
 - synced and got the problem,
 - removed uninstalled boursorama and deleted the accounts,
 - installed boursorama from the registry and set it up again,
 - synced and got the problem again.

Anything else I can help with?

**Comment by orandin** [comment]
> I somehow have 2 versions of boursorama installed on this cozy 

It's maybe the root cause of your problem. Normally, you should have one Boursorama Konnector on your instance to avoid any conflict. When you removed the boursorama konnector, did you delete the data from the database?

**Comment by nitnelave** [comment]
Sorry, I forgot to answer here after we talked on IRC.

I tried setting it up on a fresh new cozy with an empty database, and the problem came up again, so it's not because of the conflicting versions.

**Comment by orandin** [comment]
Strange... The conflict is on `io.cozy.bank.groups` doctype, but the Konnector doesn't create `io.cozy.bank.groups` of itself. An investigation is needed. 

In the meantime, I have found this script that can potentially help you: [mergeDuplicateBankAccounts.js](https://github.com/cozy/ACH/blob/master/scripts/banking/mergeDuplicateBankAccounts.js)

**Comment by nitnelave** [comment]
Actually we decided to use Bankin' in the meantime.
